#!/usr/bin/env python3
"""
Tests for Main Module
Generated by Project Prometheus
"""

import pytest
from pathlib import Path
import sys

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from main import load_config
from utils import set_seed, format_time, ensure_dir


class TestMain:
    """Tests for main module."""

    def test_load_config(self):
        """Test configuration loading."""
        config_path = Path(__file__).parent.parent / "config.yaml"
        if config_path.exists():
            config = load_config(str(config_path))
            assert "project" in config
            assert "name" in config["project"]

    def test_config_structure(self):
        """Test configuration has required fields."""
        config_path = Path(__file__).parent.parent / "config.yaml"
        if config_path.exists():
            config = load_config(str(config_path))
            required_keys = ["project", "data", "experiment"]
            for key in required_keys:
                assert key in config, f"Missing required config key: {key}"


class TestUtils:
    """Tests for utility functions."""

    def test_set_seed(self):
        """Test random seed setting."""
        set_seed(42)
        import random
        val1 = random.random()

        set_seed(42)
        val2 = random.random()

        assert val1 == val2, "Seed setting should produce reproducible results"

    def test_format_time_seconds(self):
        """Test time formatting for seconds."""
        result = format_time(30.5)
        assert "s" in result

    def test_format_time_minutes(self):
        """Test time formatting for minutes."""
        result = format_time(120)
        assert "m" in result

    def test_format_time_hours(self):
        """Test time formatting for hours."""
        result = format_time(7200)
        assert "h" in result

    def test_ensure_dir(self, tmp_path):
        """Test directory creation."""
        test_dir = tmp_path / "test_dir"
        result = ensure_dir(str(test_dir))
        assert result.exists()
        assert result.is_dir()


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
