#!/usr/bin/env python3
"""
Utility Functions
Generated by Project Prometheus
"""

import json
import random
from pathlib import Path
from typing import Any, Dict, List


def set_seed(seed: int) -> None:
    """Set random seed for reproducibility."""
    random.seed(seed)


def save_json(data: Dict[str, Any], filepath: str) -> None:
    """Save data to JSON file."""
    Path(filepath).parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, "w") as f:
        json.dump(data, f, indent=2)


def load_json(filepath: str) -> Dict[str, Any]:
    """Load data from JSON file."""
    with open(filepath, "r") as f:
        return json.load(f)


def ensure_dir(dirpath: str) -> Path:
    """Ensure directory exists, create if not."""
    path = Path(dirpath)
    path.mkdir(parents=True, exist_ok=True)
    return path


def format_time(seconds: float) -> str:
    """Format seconds into human-readable string."""
    if seconds < 60:
        return f"{seconds:.2f}s"
    elif seconds < 3600:
        minutes = seconds / 60
        return f"{minutes:.2f}m"
    else:
        hours = seconds / 3600
        return f"{hours:.2f}h"
